sudo: required
services:
  - docker

before_install:
  - docker build -t yuweib/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run yuweib/react-test npm run test -- --coverage

after_success:
  - docker build -t yuweib/multi-client ./client
  - docker build -t yuweib/multi-nginx ./nginx
  - docker build -t yuweib/multi-server ./server
  - docker build -t yuweib/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push to Docker hub
  - docker push yuweib/multi-client
  - docker push yuweib/multi-nginx
  - docker push yuweib/multi-server
  - docker push yuweib/multi-worker